### ISSUE TITLE
Cyclical dependency detection false positive with open generic service

### ISSUE THREAD

**Issue by halter73** [ninject/Ninject#143]
The following code will throw a `Ninject.ActivationException` in the call to `Get` claiming that a "A cyclical dependency was detected between the constructors of two services."

Even though `IGeneric<>` is resolved twice, there isn't a cyclical dependency because `IGeneric<>` is activated with two different type parameters which changes the type of its dependency.

```C#
class Program
{
    static void Main(string[] args)
    {
        var kernel = new StandardKernel();

        kernel.Bind(typeof(IGeneric<>)).To(typeof(Generic<>));

        // Uncomment the following line to avoid the ActivationException
        //kernel.Bind<IGeneric<IServiceA>>().To<Generic<ServiceA>>();

        kernel.Bind<IServiceA>().To<ServiceA>();
        kernel.Bind<IServiceB>().To<ServiceB>();

        var service = kernel.Get<IGeneric<IServiceA>>();
    }
}

interface IGeneric<out T>
{
}

interface IServiceA
{
}

interface IServiceB
{
}

class Generic<T> : IGeneric<T>
{
    public Generic(T foo)
    {
    }
}

class ServiceA : IServiceA
{
    public ServiceA(IGeneric<IServiceB> bar)
    {
    }
}

class ServiceB : IServiceB
{
}
```

As indicated by the comment in the Main method, you can work around this exception by registering a closed generic service (i.e. `IGeneric<IServiceA>` or `IGeneric<IServiceB>`). If you do this, the call to `Get` will return an instance of `Generic<IServiceA>` as expected.

I think this is a bug because the closed generic registration should be subsumed by the open generic registration.

The full exception message reads as follows:
```
Ninject.ActivationException: Error activating IGeneric{IServiceB} using binding from IGeneric{T} to Generic{T}
A cyclical dependency was detected between the constructors of two services.

Activation path:
  3) Injection of dependency IGeneric{IServiceB} into parameter bar of construct or of type ServiceA
  2) Injection of dependency IServiceA into parameter foo of constructor of type Generic{IServiceA}
  1) Request for IGeneric{IServiceA}

Suggestions:
  1) Ensure that you have not declared a dependency for IGeneric{IServiceB} on any implementations of the service.
  2) Consider combining the services into a single one to remove the cycle.
  3) Use property injection instead of constructor injection, and implement IInitializable
     if you need initialization logic to be run after property values have been injected.

   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Ninject.Planning.Targets.Target`1.GetValue(Type service, IContext parent)
   at Ninject.Planning.Targets.Target`1.ResolveWithin(IContext parent)
   at Ninject.Activation.Providers.StandardProvider.GetValue(IContext context, ITarget target)
   at Ninject.Activation.Providers.StandardProvider.<>c__DisplayClass4.<Create>b__2(ITarget target)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Ninject.Planning.Targets.Target`1.GetValue(Type service, IContext parent)
   at Ninject.Planning.Targets.Target`1.ResolveWithin(IContext parent)
   at Ninject.Activation.Providers.StandardProvider.GetValue(IContext context, ITarget target)
   at Ninject.Activation.Providers.StandardProvider.<>c__DisplayClass4.<Create>b__2(ITarget target)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Ninject.ResolutionExtensions.Get[T](IResolutionRoot root, IParameter[] parameters)
   at NinjectIssue.Program.Main(String[] args) in Program.cs:line 21
```

**Comment by yishaigalatzer** [comment]
Any update on the status for this?

**Comment by yishaigalatzer** [comment]
We have made a fix where we don't register some of the services as open generics. The issue in ninject still exists and will break user code (or potentially other framework code)

**Comment by jupaol** [comment]
Any update on this?
