### ISSUE TITLE
An exception is thrown when registered type is derived from MarshalByRef class

### ISSUE THREAD

**Issue by kfrajtak** [ninject/Ninject#174]
Hi, 
I have run into the following issue:

    System.TypeInitializationException: The type initializer for 'ClassA' threw an exception. --->    
    System.Runtime.Remoting.RemotingException: Attempted to call a method declared on type 'Ninject.IInitializable' on an object which exposes 'ClassB'.
    Server stack trace: 
      at System.Runtime.Remoting.Messaging.StackBuilderSink.VerifyIsOkToCallMethod(Object server, IMethodMessage msg)
      at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

    Exception rethrown at [0]: 
      at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
      at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
      at Ninject.IInitializable.Initialize()
      at Ninject.Activation.Strategies.InitializableStrategy.<Activate>b__0(IInitializable x) in InitializableStrategy.cs:line 28

And the problem is that NInject tries to call `Ninject.IInitializable.Initialize()` on remoting proxy (`ClassB`) and that fails since that class does not implement `Ninject.IInitializable` interface.

The workaround I used was to inherit from `StandardKernel`, remove `InitializableStrategy` from `Components` collection and add my own strategy that does not try to invoke `Initialize` method when the `reference` is instance of `MarshalByRef` class.

    public class RemotingProxyAwareInitializableStrategy : ActivationStrategy
    {
        public override void Activate(IContext context, InstanceReference reference)
        {
            if(reference.Is<MarshalByRefObject>())
            {
                return;
            }

            reference.IfInstanceIs<IInitializable>(x => x.Initialize());
        }
    }

I understand that this is not a common scenario (and not an issue at all) and it might be entirely wrong, and NInject was not designed to handle all various scenarios, but I just wanted to know your opinion.
Thanks,
Karel

**Comment by scott-xu** [comment]
Why your ClassA implement IInitializable?

**Comment by kfrajtak** [comment]
It does not, `ClassA` constructor is a location where `Kernel.Get<ClassB>()` is invoked (yes, I am accessing the Kernel directly).

**Comment by scott-xu** [comment]
Can you please send me a sample? scott-xu at msn.com
