### ISSUE TITLE
Exception: Method not found: 'System.Collections.Generic.IList`1<Ioc.Modules.IocRegistration> Ioc.Modules.PackageLocator.GetAllRegistrations()'.

### ISSUE THREAD

**Issue by BvdVen** [ninject/Ninject#223]
When I create execute the following code (From Global.asax Application_Start):
` var packageLocator = new PackageLocator().ProbeBinFolderAssemblies();
Ioc.Modules.Ninject.Module module = new Ioc.Modules.Ninject.Module(packageLocator);
_ninject = new StandardKernel(module);`
I get an exception on the "new StandardKernel(module)":

> Exception information: 
    Exception type: HttpException 
    Exception message: Method not found: 'System.Collections.Generic.IList`1<Ioc.Modules.IocRegistration> Ioc.Modules.PackageLocator.GetAllRegistrations()'.
   at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
Method not found: 'System.Collections.Generic.IList`1<Ioc.Modules.IocRegistration> Ioc.Modules.PackageLocator.GetAllRegistrations()'.
   at Ioc.Modules.Ninject.Module.Load()
   at Ninject.KernelBase.Load(IEnumerable`1 m)

What did I do wrong?

**Comment by BvdVen** [comment]
Not an error of Ninject...
