### ISSUE TITLE
The invoked member is not supported in a dynamic assembly.

### ISSUE THREAD

**Issue by takinosaji** [ninject/Ninject#225]
In different applications when using `kernel.Load(AppDomain.CurrentDomain.GetAssemblies());` receiving an error: The invoked member is not supported in a dynamic assembly.

Detailed string:

Type = System.NotSupportedException
Message = The invoked member is not supported in a dynamic assembly.
Source = mscorlib
TargetSite = System.Type[] GetExportedTypes()
StackTrace =    at System.Reflection.Emit.InternalAssemblyBuilder.GetExportedTypes()
   at Ninject.Infrastructure.Language.ExtensionsForAssembly.GetNinjectModules(Assembly assembly)
   at Ninject.KernelBase.<Load>b__2(Assembly asm)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ninject.KernelBase.Load(IEnumerable`1 m)
   at Ninject.KernelBase.Load(IEnumerable`1 assemblies)
   at Dolphin.Host.Startup.CreateKernel() in .....
HResult = -2146233067

**Comment by Gusdor** [comment]
This error is occurring because Assembly.Load cannot be called upon dynamic assemblies. You must filter out the dynamic assemblies before using them.

`kernel.Load(AppDomain.CurrentDomain.GetAssemblies().Where(p => !p.IsDynamic));`

**Comment by elprotto** [comment]
Works for me!
