### ISSUE TITLE
[v3.3.4] GarbageCollectionCachePruner.Stop throws NullReferenceException

### ISSUE THREAD

**Issue by yosqueoy** [ninject/Ninject#365]
Hi forks,

I called IKernel.Dispose() in my Dispose method and got NullReferenceException. The version is v3.3.4.

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Ninject.Activation.Caching.GarbageCollectionCachePruner.Stop()
   at Ninject.Activation.Caching.GarbageCollectionCachePruner.Dispose(Boolean)
   at Ninject.Infrastructure.Disposal.DisposableObject.Dispose()
   at Ninject.Components.ComponentContainer.Dispose(Boolean)
   at Ninject.Infrastructure.Disposal.DisposableObject.Dispose()
   at Ninject.KernelBase.Dispose(Boolean)
   at Ninject.Infrastructure.Disposal.DisposableObject.Dispose()
   at ...
```
I guess `timer` could be null at the line below.

https://github.com/ninject/Ninject/blob/master/src/Ninject/Activation/Caching/GarbageCollectionCachePruner.cs#L117

**Comment by scott-xu** [comment]
Sorry for the late reply but can you please provide more context about the issue? In theory the `timer` should not be null. Is your `Dispose()` in multi-thread condition?
